Repository LLNL/DiHydrogen, pull requests merged in 2024-07, with the labels that each got.

#138 Improve error handling/reporting
  include/h2/core/sync.hpp
  include/h2/tensor/copy.hpp
  include/h2/tensor/dist_tensor.hpp
  include/h2/tensor/dist_tensor_base.hpp
  include/h2/tensor/dist_utils.hpp
  include/h2/tensor/fixed_size_tuple.hpp
  include/h2/tensor/proc_grid.hpp
  include/h2/tensor/strided_memory.hpp
  include/h2/tensor/tensor.hpp
  include/h2/tensor/tensor_base.hpp
  include/h2/tensor/tensor_utils.hpp
  include/h2/utils/CMakeLists.txt
  include/h2/utils/Error.hpp
  include/h2/utils/environment_vars.hpp
  include/h2/utils/strings.hpp
  src/utils/CMakeLists.txt
  src/utils/Error.cpp
  src/utils/environment_vars.cpp
  test/unit_test/utils/CMakeLists.txt
  test/unit_test/utils/unit_test_environment_vars.cpp
  test/unit_test/utils/unit_test_error.cpp
  test/unit_test/utils/unit_test_strings.cpp
Labels: enhancement

#145 Fix compilation issue
  include/h2/utils/Error.hpp
  src/utils/Error.cpp
Labels: bug

#146 Fix an issue with El::Device vs h2::Device ADL
  include/h2/core/device.hpp
Labels: bug

#150 Check for APUs on ROCm platforms
  src/gpu/rocm/runtime.cpp
Labels: enhancement

#154 Add missing header for ROCm debug build
  legacy/include/distconv/tensor/tensor_base.hpp
Labels: bug, review requested, HIP/ROCM

#155 Cleanup include tree installation artifacts
  include/h2/core/CMakeLists.txt
  include/h2/meta/typelist/__template.hpp
  include/h2/tensor/hydrogen_interop/CMakeLists.txt
Labels: bug, build, review requested

#143 Clone and initial copy support for DistTensor
  include/h2/tensor/CMakeLists.txt
  include/h2/tensor/copy.hpp
  include/h2/tensor/copy_buffer.hpp
  include/h2/tensor/dist_tensor.hpp
  include/h2/tensor/proc_grid.hpp
  include/h2/tensor/strided_memory.hpp
  include/h2/tensor/tensor.hpp
  test/unit_test/tensor/CMakeLists.txt
  test/unit_test/tensor/unit_test_copy.cpp
  test/unit_test/tensor/unit_test_dist_copy.cpp
  test/unit_test/tensor/unit_test_dist_tensor.cpp
  test/unit_test/tensor/unit_test_proc_grid.cpp
  test/unit_test/tensor/unit_test_raw_buffer.cpp
  test/unit_test/tensor/unit_test_strided_memory.cpp
  test/unit_test/tensor/unit_test_tensor.cpp
  test/unit_test/tensor/utils.hpp
Labels: enhancement

#157 Stream and synchronization improvements
  include/h2/core/device.hpp
  include/h2/core/sync.hpp
  include/h2/gpu/cuda/runtime.hpp
  include/h2/gpu/rocm/runtime.hpp
  include/h2/tensor/copy_buffer.hpp
  test/unit_test/CMakeLists.txt
  test/unit_test/core/unit_test_sync.cpp
  test/unit_test/mpi_utils.hpp
  test/unit_test/tensor/unit_test_copy.cpp
  test/unit_test/tensor/unit_test_dist_tensor.cpp
  test/unit_test/tensor/unit_test_raw_buffer.cpp
  test/unit_test/tensor/unit_test_strided_memory.cpp
  test/unit_test/tensor/unit_test_tensor.cpp
  test/unit_test/tensor/utils.hpp
  test/unit_test/wait.cu
  test/unit_test/wait.hpp
Labels: bug, enhancement
