Repository LLNL/DiHydrogen, pull requests merged in 2024-09, with the labels that each got.

#166 Dynamic (runtime) dispatch
  .gitlab/build-and-test-lassen.yml
  CMakeLists.txt
  include/h2/core/dispatch.hpp
  include/h2/core/types.hpp
  include/h2/tensor/CMakeLists.txt
  include/h2/tensor/base_utils.hpp
  include/h2/tensor/copy.hpp
  include/h2/tensor/tensor.hpp
  include/h2/utils/CMakeLists.txt
  include/h2/utils/IntegerMath.hpp
  include/h2/utils/unique_ptr_cast.hpp
  scripts/dispatch_gen.py
  src/core/dispatch.cpp
  src/tensor/CMakeLists.txt
  src/tensor/base_utils.cpp
  src/tensor/copy.cpp
  src/utils/CMakeLists.txt
  test/unit_test/core/unit_test_dispatch.cpp
  test/unit_test/tensor/unit_test_copy.cpp
  test/unit_test/utils/CMakeLists.txt
  test/unit_test/utils/unit_test_unique_ptr_cast.cpp
Labels: enhancement

#181 More cleanup
  include/h2/Version.hpp
  include/h2/gpu/error.hpp
  include/h2/gpu/logger.hpp
  include/h2/gpu/rocm/memory_utils.hpp
  include/h2/meta/Core.hpp
  include/h2/meta/PartialFunctions.hpp
  include/h2/meta/TypeList.hpp
  include/h2/meta/core/Eq.hpp
  include/h2/meta/core/IfThenElse.hpp
  include/h2/meta/core/Invocable.hpp
  include/h2/meta/core/Lazy.hpp
  include/h2/meta/core/SFINAE.hpp
  include/h2/meta/core/ValueAsType.hpp
  include/h2/meta/partial_functions/Apply.hpp
  include/h2/meta/partial_functions/MakeFunction.hpp
  include/h2/meta/partial_functions/Placeholders.hpp
  include/h2/meta/typelist/CMakeLists.txt
  include/h2/patterns/factory/CopyFactory.hpp
  include/h2/patterns/factory/DefaultErrorPolicy.hpp
  include/h2/patterns/factory/NullptrErrorPolicy.hpp
  include/h2/patterns/factory/ObjectFactory.hpp
  include/h2/patterns/factory/PrototypeFactory.hpp
  include/h2/patterns/multimethods/SwitchDispatcher.hpp
  include/h2/utils/Error.hpp
  include/h2/utils/Logger.hpp
  legacy/include/distconv/dnn_backend/backend.hpp
  legacy/include/distconv/runtime_gpu.hpp
  legacy/include/distconv/util/util_gpu_dnn.hpp
  src/utils/logger_internals.hpp
  src/utils/logging/hostname_pattern.hpp
  src/utils/logging/rank_pattern.hpp
  src/utils/logging/size_pattern.hpp
Labels: review requested

#183 Use H2 meta tools more
  include/h2/loops/cpu_loops.hpp
  include/h2/loops/gpu_loops.cuh
  include/h2/loops/gpu_vec_helpers.cuh
  include/h2/meta/typelist/ToFromTuple.hpp
  include/h2/utils/CMakeLists.txt
  include/h2/utils/function_traits.hpp
  include/h2/utils/tuple_utils.hpp
  test/static_test/utils/CMakeLists.txt
  test/static_test/utils/static_test_function_traits.cpp
  test/static_test/utils/static_test_tuple_utils.cpp
Labels: enhancement, review requested, New H2

#184 Add a log-time multimethod dispatcher
  include/h2/patterns/multimethods/CMakeLists.txt
  include/h2/patterns/multimethods/MapDispatcher.hpp
  test/unit_test/patterns/multimethods/CMakeLists.txt
  test/unit_test/patterns/multimethods/unit_test_map_dispatcher.cpp
Labels: review requested

#186 Adjust corona CI to target CPU builds
  .gitlab/build-and-test-corona.yml
  .gitlab/configure_deps.sh
  .gitlab/setup_env.sh
  cmake/modules/H2CXXCodeCoverage.cmake
Labels: review requested

#187 TypeList library: Cleanup Find and add FindIf
  include/h2/meta/typelist/Find.hpp
  test/static_test/meta/typelist/static_test_find.cpp
Labels: review requested

#161 Patch an issue with ROCm 6.2.0 build
  CMakeLists.txt
Labels: build, HIP/ROCM
