Repository LLNL/DiHydrogen, pull requests merged in 2024-08, with the labels that each got.

#159 Printing tensors and other miscellanea
  include/h2/core/CMakeLists.txt
  include/h2/core/allocator.hpp
  include/h2/core/sync.hpp
  include/h2/tensor/copy.hpp
  include/h2/tensor/fixed_size_tuple.hpp
  include/h2/tensor/hydrogen_interop/local_tensor_interop.hpp
  include/h2/tensor/io.hpp
  include/h2/tensor/raw_buffer.hpp
  include/h2/tensor/strided_memory.hpp
  include/h2/tensor/tensor.hpp
  include/h2/tensor/tensor_utils.hpp
  include/h2/tensor/tuple_utils.hpp
  include/h2/utils/Error.hpp
  test/static_test/tensor/fixed_size_tuple.cpp
  test/static_test/tensor/tensor_types.cpp
  test/unit_test/core/CMakeLists.txt
  test/unit_test/core/unit_test_allocator.cpp
  test/unit_test/tensor/CMakeLists.txt
  test/unit_test/tensor/unit_test_copy.cpp
  test/unit_test/tensor/unit_test_hydrogen_interop.cpp
  test/unit_test/tensor/unit_test_io.cpp
  test/unit_test/tensor/unit_test_raw_buffer.cpp
  test/unit_test/tensor/unit_test_strided_memory.cpp
  test/unit_test/tensor/unit_test_tensor.cpp
Labels: enhancement

#160 Add Foldl and Foldr type functions
  include/h2/meta/typelist/Reduce.hpp
  test/static_test/meta/typelist/CMakeLists.txt
  test/static_test/meta/typelist/static_test_reduce.cpp
Labels: review requested

#162 Fix developer build/warnings
  CMakeLists.txt
  include/h2/core/allocator.hpp
  include/h2/tensor/copy.hpp
  include/h2/tensor/fixed_size_tuple.hpp
  include/h2/tensor/io.hpp
  include/h2/tensor/proc_grid.hpp
  include/h2/utils/Describable.hpp
  include/h2/utils/strings.hpp
  src/gpu/cuda/runtime.cpp
  test/static_test/tensor/fixed_size_tuple.cpp
  test/unit_test/core/unit_test_sync.cpp
  test/unit_test/mpi_cumulative_reporter.cpp
  test/unit_test/tensor/unit_test_copy.cpp
  test/unit_test/tensor/unit_test_dist_tensor.cpp
  test/unit_test/tensor/unit_test_hydrogen_interop.cpp
  test/unit_test/tensor/unit_test_raw_buffer.cpp
  test/unit_test/tensor/unit_test_strided_memory.cpp
  test/unit_test/tensor/unit_test_tensor.cpp
  test/unit_test/utils/unit_test_describable.cpp
Labels: bug

#164 Fix missing header install.
  include/h2/meta/typelist/CMakeLists.txt
Labels: bug
